#ifndef DATA_BASE_TAKE_3_CONFIG_H
#define DATA_BASE_TAKE_3_CONFIG_H

#define FILE_GRANULARITY 8
#define MINIMAL_TUPLE_SIZE 256
#define VAL "22"
#define SINGLE_TUPLE_VALUE_SIZE 8
#define OFFSET_VALUE_SIZE 8
#define NULL_VALUE 0
#define BIG_ENDIAN_SIGNATURE 0xFFFE
#define MIN_ID_ARRAY_SIZE 1
#define TAB "   "

#define STRING_TYPE 0
#define INTEGER_TYPE 1
#define BOOLEAN_TYPE 2
#define FLOAT_TYPE 3

#define TUPLE_ID "id"
#define STAR "*"

#endif //DATA_BASE_TAKE_3_CONFIG_H
